---
- name: Import the Erlang RPM key
  rpm_key:
    key: https://packages.erlang-solutions.com/rpm/erlang_solutions.asc

- name: Add the Erlang Solutions repository
  yum_repository:
    name: erlang-solutions
    description: "{{ ansible_distribution }} $releasever - $basearch - Erlang Solutions"
    baseurl: https://packages.erlang-solutions.com/rpm/centos/$releasever/$basearch
    gpgcheck: True
    gpgkey: https://packages.erlang-solutions.com/rpm/erlang_solutions.asc

- name: Install Erlang
  yum:
    name: erlang

- name: Add the ConVirt Dependencies repository
  yum_repository:
    name: convirt-dep
    description: ConVirt Dependencies
    baseurl: "http://www.convirture.com/repos/deps/RHEL/{{ ansible_distribution_major_version }}.x"
    gpgcheck: False
    gpgkey: http://www.convirture.com/repos/convirture_packaging_pub_key
  when: rabbitmq_version | version_compare('3.6.2', '>=') and ansible_distribution_major_version in ['5','6']

- name: Import the RabbitMQ RPM key
  rpm_key:
    key: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc

- name: Download the RabbitMQ package
  get_url:
    url: "https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version.split('-')[0] }}/rabbitmq-server-{{ rabbitmq_version }}{% if rabbitmq_version | version_compare('3.6.6', '>=') %}.el{{ ansible_distribution_major_version }}{% endif %}.noarch.rpm"
    dest: "/usr/src/rabbitmq-server-{{ rabbitmq_version }}.rpm"

- name: Install RabbitMQ
  yum:
    name: "/usr/src/rabbitmq-server-{{ rabbitmq_version }}.rpm"
